// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_gwtpykGOaYzTO09pRXMegZOgEvTUkMU',
    appId: '1:674891666979:web:6d5e44ce264c5a9bf70396',
    messagingSenderId: '674891666979',
    projectId: 'smarthomearduino-ff371',
    authDomain: 'smarthomearduino-ff371.firebaseapp.com',
    databaseURL: 'https://smarthomearduino-ff371-default-rtdb.firebaseio.com',
    storageBucket: 'smarthomearduino-ff371.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAl79kCM806FT26vK-7u53RG7VxPGFDeA',
    appId: '1:674891666979:android:cafd5e77eb4ff200f70396',
    messagingSenderId: '674891666979',
    projectId: 'smarthomearduino-ff371',
    databaseURL: 'https://smarthomearduino-ff371-default-rtdb.firebaseio.com',
    storageBucket: 'smarthomearduino-ff371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5dnepCAcTqNi16vV9o6Ocp6lGFnzbFJo',
    appId: '1:674891666979:ios:d08dbf0a195579f1f70396',
    messagingSenderId: '674891666979',
    projectId: 'smarthomearduino-ff371',
    databaseURL: 'https://smarthomearduino-ff371-default-rtdb.firebaseio.com',
    storageBucket: 'smarthomearduino-ff371.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5dnepCAcTqNi16vV9o6Ocp6lGFnzbFJo',
    appId: '1:674891666979:ios:d08dbf0a195579f1f70396',
    messagingSenderId: '674891666979',
    projectId: 'smarthomearduino-ff371',
    databaseURL: 'https://smarthomearduino-ff371-default-rtdb.firebaseio.com',
    storageBucket: 'smarthomearduino-ff371.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );
}
