// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2h_LbZjJoVXJO9Pl1iCYO3qurdczBZzM',
    appId: '1:276509482974:web:18c0b1ddba92191a31c74f',
    messagingSenderId: '276509482974',
    projectId: 'smarthome-c49b9',
    authDomain: 'smarthome-c49b9.firebaseapp.com',
    storageBucket: 'smarthome-c49b9.appspot.com',
    measurementId: 'G-7J9CSV3PS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWXuWJVNNWjC_-ZLjJpXxtsvnkO4Vo24',
    appId: '1:276509482974:android:2869db30c2df7c4131c74f',
    messagingSenderId: '276509482974',
    projectId: 'smarthome-c49b9',
    storageBucket: 'smarthome-c49b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-mK8gQndFBGDmgM1_ln6UzVrBd9ehJc',
    appId: '1:276509482974:ios:dbb8d0e3891f6bf231c74f',
    messagingSenderId: '276509482974',
    projectId: 'smarthome-c49b9',
    storageBucket: 'smarthome-c49b9.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-mK8gQndFBGDmgM1_ln6UzVrBd9ehJc',
    appId: '1:276509482974:ios:dbb8d0e3891f6bf231c74f',
    messagingSenderId: '276509482974',
    projectId: 'smarthome-c49b9',
    storageBucket: 'smarthome-c49b9.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );
}
